name: Release macOS

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install macOS dependencies
        run: |
          brew install create-dmg

      - name: Install dependencies
        run: |
          # Ensure we use public registry without any authentication
          npm config set registry https://registry.npmjs.org/
          npm install --no-audit --no-fund

      - name: Build Tauri app
        run: npm run tauri build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/bundle/dmg/*.dmg
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
